export const Users = [
    {
        id: 1,
        pizzaName: "Mexiconii",
        pizzaImg: "/assets/Mexican_Green_Wave.jpg",
        pizzaDesc: " Cheese I Golden Corn Cheese Golden Corn Chunky paneer with crisp crisp it..",
        pizzaSize: "Regular Large Medium",
        pizzaAvailable: 5,
    },
    {
        id: 2,
        pizzaName: "Nonveggy",
        pizzaImg: "/assets/my-nonveg.jpg",
        pizzaDesc: "Paneer and  Cheese Golden CornCheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Medium Regular Large",
        pizzaAvailable: 1,
    },
    {
        id: 3,
        pizzaName: "ExtraVaganz",
        pizzaImg: "/assets/Veg_Extravaganz.jpg",
        pizzaDesc: "A hugely popular margherita,Cheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Large Regular Medium",
        pizzaAvailable: 4,
    },
    {
        id: 4,
        pizzaName: "Margherit",
        pizzaImg: "/assets/Margherit.jpg",
        pizzaDesc: "The ever-popular Margherita Cheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Regular Large Medium ",
        pizzaAvailable: 3,
    },
    {
        id: 5,
        pizzaName: "PannerTikka",
        pizzaImg: "/assets/Fresh_Veggie.jpg",
        pizzaDesc: "A pizza that goes ballistic Cheese Golden Corn Chunky paneer with crisp crisp..",
        pizzaSize: "Medium Reagular Medium",
        pizzaAvailable: 2,

    },
    {
        id: 6,
        pizzaName: "Farmhouse",
        pizzaImg: "/assets/Farmhouse.jpg",
        pizzaDesc: "Chunky paneer with crisp Cheese Golden Corn Chunky paneer with crisp crisp ..",
        pizzaSize: "Large Regular Medium",
        pizzaAvailable: 4,
    },
    {
        id: 7,
        pizzaName: "Mexiconii",
        pizzaImg: "/assets/Mexican_Green_Wave.jpg",
        pizzaDesc: " Cheese I Golden Corn Cheese Golden Corn Chunky paneer with crisp crisp it..",
        pizzaSize: "Regular Large Medium",
        pizzaAvailable: 6,
    },
    {
        id: 8,
        pizzaName: "Nonveggy",
        pizzaImg: "/assets/my-nonveg.jpg",
        pizzaDesc: "Paneer and  Cheese Golden CornCheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Medium Regular Large",
        pizzaAvailable: 4,
    },
    {
        id: 9,
        pizzaName: "ExtraVaganz",
        pizzaImg: "/assets/Veg_Extravaganz.jpg",
        pizzaDesc: "A hugely popular margherita,Cheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Large Regular Medium",
        pizzaAvailable: 7,
    },
    {
        id: 10,
        pizzaName: "Margherit",
        pizzaImg: "/assets/Margherit.jpg",
        pizzaDesc: "The ever-popular Margherita Cheese Golden Corn Chunky paneer with crisp ..",
        pizzaSize: "Regular Large Medium ",
        pizzaAvailable: 4,
    },
    {
        id: 11,
        pizzaName: "PannerTikka",
        pizzaImg: "/assets/Fresh_Veggie.jpg",
        pizzaDesc: "A pizza that goes ballistic Cheese Golden Corn Chunky paneer with crisp crisp..",
        pizzaSize: "Medium Reagular Medium",
        pizzaAvailable: 9,
    },
    {
        id: 12,
        pizzaName: "Farmhouse",
        pizzaImg: "/assets/Farmhouse.jpg",
        pizzaDesc: "Chunky paneer with crisp Cheese Golden Corn Chunky paneer with crisp crisp ..",
        pizzaSize: "Large Regular Medium",
        pizzaAvailable: 2,
    },

];